# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeLasted', models.FloatField()),
                ('maxUploadValue', models.FloatField()),
                ('minUploadValue', models.FloatField()),
                ('avgUploadValue', models.FloatField()),
                ('totalUploadValue', models.FloatField()),
                ('maxDownloadValue', models.FloatField()),
                ('minDownloadValue', models.FloatField()),
                ('avgDownloadValue', models.FloatField()),
                ('totalDownloadValue', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TempRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maxd', models.FloatField()),
                ('mind', models.FloatField()),
                ('totald', models.FloatField()),
                ('maxu', models.FloatField()),
                ('minu', models.FloatField()),
                ('totalu', models.FloatField()),
                ('time', models.FloatField()),
            ],
        ),
    ]
