# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 18:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowVisualization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
