# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-16 20:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowVisualization', '0002_datarecord_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='datarecord',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
    ]
